# Generated by Django 4.2.3 on 2023-07-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Finance', 'Finance'), ('IT', 'IT')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
